### PR TITLE
Neighborhood city sortby

### PR DESCRIPTION
**Pull request by pjaudiomv**
this adds sort by neighborhood and city option, however this is worked off of seperate branch from previous pull request. not sure if i should just branch current radius/bread unstable and make PR from that.

### CODE REVIEW

**Comment by pjaudiomv** [comment]
so i should of worked off two separate branches from unstable?

**Comment by pjaudiomv** [comment]
in other words i should keep unstable up to date with its upstream and work off seperate branches

**Comment by radius314** [comment]
correct.  That way each “feature” can be merged independently.

**Comment by pjaudiomv** [comment]
gotcha makes sense

**Comment by radius314** [comment]
in this case this PR #43 was build on top of #42, so if #43 got merged, it would render #42 useless because it has everything already.  it creates an unnecessary dependency.

**Comment by pjaudiomv** [comment]
understood, I shall use separate branches now. I've been burned in the passed not doing that so i think the pain is great enough now.

**Pull request merged**
