### PR TITLE
last cred removal

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
alright just checked the rest of them too

**Comment by radius314** [comment]
one thing we might need to address is that the nalogo is hosted at nameetinglist.org, that might burn us one day

**Comment by radius314** [comment]
not for today for sure

**Comment by radius314** [comment]
i'll ticket it

**Comment by pjaudiomv** [comment]
i thought about that too, but then said screw it. it is stored locally in that same folder. otherwise move it to bmlt.app haha

**Comment by radius314** [comment]
#49 raised

**Pull request merged**
