### PR TITLE
fonts spacing issue

### PR DESCRIPTION
**Pull request by pjaudiomv**
#17 NOT MEANT TO BE MERGED just trying to show how I was able to fix this issue, im not well versed in the fine arts of mPDF. this did fix issue and all works as intended. checked with editing pages and spacing.

### CODE REVIEW

**Comment by radius314** [comment]
why would we not merge this?

**Comment by pjaudiomv** [comment]
i think there could be an inherit problem with it though i havent tested it. the way i wrote that if someone picks arial, courier or times and then tries to use a different font besides those three they may not be able to and would then default to one of those. not sure though just a scenario i went over in my head.

**Comment by radius314** [comment]
can you test it?

**Comment by pjaudiomv** [comment]
sure thing

**Comment by pjaudiomv** [comment]
yea this works as expected and same as current version. you only have the three font options in the editor anyway, if you wanted to specifically specify a different one you would have to go into the text (code) editor and then it would just default to one of the three (times, arial, courier)

**Comment by pjaudiomv** [comment]
you could also shed a bunch of weight by dumping the asian font packs Sun-ExtA.ttf, Sun-ExtB.ttf these eat up 40mbs although if you ever had an asian translation youd have to add them back in

**Comment by radius314** [comment]
No reason to remove them.

**Comment by radius314** [comment]
Functionality should never require going into a code editor, if you do then
it’s missing something.

**Comment by pjaudiomv** [comment]
that's a good point, and kinda what i thought. if someone wants to mess around in the code editor that's on them. this should be fine then i would think. besides the commenting out of code that was there and some formatting stuff

**Comment by radius314** [comment]
need to test this out.

**Pull request merged**
